---
- name: Install Pgpool
  become: true
  package: name={{ item }} state=latest
  with_items:
   - pgpool-II-96
   - pgpoolAdmin

- name: short command wrapper
  template:
     src: pcpctl.j2
     dest: /usr/local/bin/pcpctl
     owner: root
     group: root
     mode: 0755

- name: attach all pg nodes
  command: " /usr/local/bin/pcpctl attach {{ item }} "
  with_items: "{{ groups['postgres'] }}"
