---
- name: Install postgres
  become: true
  package: name={{ item }} state=latest
  with_items:
   - postgresql96-server

- name: create folder if not exist
  become: true
  file:
    path: /var/lib/pgsql/9.6/data/
    state: directory
    mode: 0700

- name: Check if folder is empty
  become: true
  shell: ls -l /var/lib/pgsql/9.6/data/ | wc -l
  register: folder

- name: Init postgres database
  become: true
  shell: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  when: folder.stdout == "1"

#- name: debug - host
#  debug:
#    msg: "{{ host }}"

- name: debug - hostvars
  debug:
    msg: "{{ groups['postgres'] }}"

- include: configuration.yml

- name: Enable postgres service
  become: true
  service:
    name: postgresql-9.6
    enabled: yes
